### ISSUE TITLE
Reminder alerts are brought over but they shouldn't be

### ISSUE THREAD

**Issue by arobertn** [utdemir/gcal-i-am-busy#2]
If the original event has a reminder, this is unfortunately copied over to the new event. Which is unwanted since it will just be a duplicate alert to the one for the original event already on your calendar. Or maybe it is not copying but doing something according to the default alert policy for events in the new calendar. In either case, it should clean the event of alerts before creating. I found [this app](https://bulkeditcalendarevents.com) useful for doing a mass edit to clear the alerts afterwards.

**Comment by utdemir** [comment]
Thanks for opening the issue.

> maybe it is not copying but doing something according to the default alert policy for events in the new calendar.

I think this is what's going on; because the script does not copy the original event, instead it creates a new event using the original events start and end date.

Handily, the Google App Script API provides a `removeAllReminders` method that we can use to delete the notifications. I committed f988d9367dc86ec35c1d1533e15e7719c71cbdf1 to do this.

However, it will only affect newly created events. If you want to apply this to existing events, you have to delete them; so the script will recreate them without notifications. I implemented a small workaround to do that, and documented that on the README (04fa81eed6f34196aba16d9ad4bf8593277ac3d9).

---

I'm closing the issue, but let me know if it does not work for you!
